version: "3"
services:
#  app:
#     container_name: node
#     restart: always
#     build: .
#     volumes:
#     - .:/usr/app/
#     - /usr/app/node_modules
#     ports:
#     - "5000:5000"
#     depends_on:
#     - mongo
#     links:
#     - mongo
#    #  command: node app
#    #  -run: node app
#  redis:
#     container_name: redis
#     image: redis


 mongo:
    container_name: mongoDB
    image: mongo
    ports:
    - "27017:27017" 
    
 node:
    image: node:12.13.0-alpine
    container_name: node
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: sh -c "node app"
    ports:
     - "5000:5000"
    depends_on: 
     - "mongo"
     - "redis"
 redis: 
    image: redis

#  nginx:
#     image: nginx
#     container_name: nginx
#     expose: 
#      - 80
#     ports:
#      - "80:80"
     