version: "3"
services:
#  website:
#         build:
#             context: .
#         command: node app
#         ports:
#             - 5000:5000
#         volumes:
#             - .:/usr/src/app
#  database:
#   image: mongo
#   environment:
#     - MONGO_INITDB_DATABASE=test1
#   ports:
#   - "27017:27017"
#   volumes:
#   - ./data/mongo:/data/db

 app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
    - "5000:5000"
    links:
    - mongo
 mongo:
    container_name: mongoDB
    image: mongo
    ports:
    - "27017:27017"


